export const invoices = [
  {
    document_number: "000120568",
    company: { name: "FusionWare" },
    date_document: new Date(2024, 9, 1),
    document: undefined,
    account_plan: undefined,
    project: undefined,
    expense_type: undefined,
    recurrence: undefined,
    supplier: { name: "Fornecedor A" },
    bank: undefined,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date(2024, 9, 10),
    date_payment: undefined,
    confirmed_status: "Pendente",
    payed_status: "Em Aberto",
    group: undefined,
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        ncm: 7031020,
        cfop: 5102,
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        purchase_quantity: 36,
        value_unit: 2.49,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
      },
      {
        name: "Vinho Tinto",
        code: "1005",
        ncm: 7049020,
        cfop: 5102,
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        purchase_quantity: 10,
        value_unit: 34.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
      },
      {
        name: "Vodka Orloff",
        code: "1007",
        ncm: 7070000,
        cfop: 5102,
        buy_unit: {
          description: "Unidade",
          abbreviation: "UN",
          unitsPerPack: 1,
        },
        purchase_quantity: 2,
        value_unit: 39.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Destilados" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 2",
        },
      },
    ],
  },
  {
    document_number: "000124798",
    company: { name: "Apex Innovations Filial" },
    date_document: new Date(2024, 9, 2),
    document: undefined,
    account_plan: undefined,
    project: undefined,
    expense_type: undefined,
    recurrence: undefined,
    supplier: { name: "Fornecedor B" },
    bank: undefined,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date(2024, 9, 10),
    date_payment: undefined,
    confirmed_status: "Pendente",
    payed_status: "Em Aberto",
    group: undefined,
    products: [
      {
        name: "Vinho Tinto",
        code: "1005",
        ncm: 7049020,
        cfop: 5102,
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        purchase_quantity: 10,
        value_unit: 34.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
      },
      {
        name: "Vodka Orloff",
        code: "1007",
        ncm: 7070000,
        cfop: 5102,
        buy_unit: {
          description: "Unidade",
          abbreviation: "UN",
          unitsPerPack: 1,
        },
        purchase_quantity: 2,
        value_unit: 39.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Destilados" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 2",
        },
      },
    ],
  },
  {
    document_number: "000892359",
    company: { name: "Apex Innovations Matriz" },
    date_document: new Date(2024, 8, 31),
    document: undefined,
    account_plan: undefined,
    project: undefined,
    expense_type: undefined,
    recurrence: undefined,
    supplier: { name: "Fornecedor C" },
    bank: undefined,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date(2024, 9, 11),
    date_payment: undefined,
    confirmed_status: "Pendente",
    payed_status: "Em Aberto",
    group: undefined,
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        ncm: 7031020,
        cfop: 5102,
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        purchase_quantity: 72,
        value_unit: 2.49,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
      },
    ],
  },
  {
    document_number: "000691459",
    company: { name: "Quantum Dynamics" },
    date_document: new Date(2024, 9, 5),
    document: undefined,
    account_plan: undefined,
    project: undefined,
    expense_type: undefined,
    recurrence: undefined,
    supplier: { name: "Fornecedor C" },
    bank: undefined,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date(2024, 9, 15),
    date_payment: undefined,
    confirmed_status: "Confirmada",
    payed_status: "Em Aberto",
    group: undefined,
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        ncm: 7031020,
        cfop: 5102,
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        purchase_quantity: 36,
        value_unit: 2.49,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
      },
      {
        name: "Vinho Tinto",
        code: "1005",
        ncm: 7049020,
        cfop: 5102,
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        purchase_quantity: 10,
        value_unit: 34.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
      },
      {
        name: "Vodka Orloff",
        code: "1007",
        ncm: 7070000,
        cfop: 5102,
        buy_unit: {
          description: "Unidade",
          abbreviation: "UN",
          unitsPerPack: 1,
        },
        purchase_quantity: 2,
        value_unit: 39.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Destilados" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 2",
        },
      },
    ],
  },
  {
    document_number: "000543731",
    company: { name: "TechNova Filial" },
    date_document: new Date(2024, 9, 5),
    document: undefined,
    account_plan: undefined,
    project: undefined,
    expense_type: undefined,
    recurrence: undefined,
    supplier: { name: "Fornecedor C" },
    bank: undefined,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date(2024, 9, 15),
    date_payment: undefined,
    confirmed_status: "Rejeitada",
    payed_status: "Em Aberto",
    group: undefined,
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        ncm: 7031020,
        cfop: 5102,
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        purchase_quantity: 36,
        value_unit: 2.49,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
      },
      {
        name: "Vinho Tinto",
        code: "1005",
        ncm: 7049020,
        cfop: 5102,
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        purchase_quantity: 10,
        value_unit: 34.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
      },
      {
        name: "Vodka Orloff",
        code: "1007",
        ncm: 7070000,
        cfop: 5102,
        buy_unit: {
          description: "Unidade",
          abbreviation: "UN",
          unitsPerPack: 1,
        },
        purchase_quantity: 2,
        value_unit: 39.9,
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Destilados" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 2",
        },
      },
    ],
  },
];
