export type NotaFiscal = {
  numNF: number;
  date: Date;
  quantity: string;
  company: string;
  supplier: string;
  description: string;
  status: "Pendente" | "Confirmada" | "Rejeitada";
};

export const inputPath = "Documentos/Strategis/Restaurante1/NFs-pendentes";

export const outputPath = "Documentos/Strategis/Restaurante1/NFs-aceitas";

export const notasFiscais: NotaFiscal[] = [
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Tomate, Alface, Batata",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 12345,
    date: new Date(2024, 9, 5),
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
    status: "Pendente",
  },
  {
    numNF: 67890,
    date: new Date(2024, 9, 6),
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
    status: "Pendente",
  },
  {
    numNF: 98765,
    date: new Date(2024, 9, 8),
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
    status: "Pendente",
  },
  {
    numNF: 54321,
    date: new Date(2024, 9, 7),
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Água Mineral, Refrigerantes, Cervejas",
    status: "Confirmada",
  },
  {
    numNF: 67891,
    date: new Date(2024, 9, 9),
    quantity: "120",
    company: "Empresa 5",
    supplier: "Fornecedor X",
    description: "Fogões industriais, Panelas de pressão, Freezer",
    status: "Confirmada",
  },
  {
    numNF: 13579,
    date: new Date(2024, 9, 10),
    quantity: "80",
    company: "Empresa 6",
    supplier: "Fornecedor X",
    description: "Facas, Colheres de aço inox, Tábua de corte",
    status: "Confirmada",
  },
  {
    numNF: 24680,
    date: new Date(2024, 9, 11),
    quantity: "300",
    company: "Empresa 7",
    supplier: "Fornecedor X",
    description: "Tomates, Alfaces, Pimentões, Cenouras",
    status: "Confirmada",
  },
  {
    numNF: 12346,
    date: new Date(2024, 9, 5),
    quantity: "90",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Sabão em pó, Desinfetante, Água sanitária",
    status: "Rejeitada",
  },
  {
    numNF: 67892,
    date: new Date(2024, 9, 6),
    quantity: "30",
    company: "Empresa 8",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Fitas adesivas, Plásticos bolha",
    status: "Rejeitada",
  },
  {
    numNF: 13580,
    date: new Date(2024, 9, 7),
    quantity: "180",
    company: "Empresa 9",
    supplier: "Fornecedor X",
    description: "Cervejas vencidas, Refrigerantes vencidos",
    status: "Rejeitada",
  },
  {
    numNF: 98766,
    date: new Date(2024, 9, 8),
    quantity: "50",
    company: "Empresa 10",
    supplier: "Fornecedor X",
    description: "Papéis A4, Canetas, Clipes de papel",
    status: "Rejeitada",
  },
];
