export type NotaFiscal = {
  numNF: number;
  date: string;
  quantity: string;
  company: string;
  supplier: string;
  description: string;
};

export const inputPath = "Documentos/Strategis/Restaurante1/NFs-pendentes";

export const outputPath = "Documentos/Strategis/Restaurante1/NFs-aceitas";

export const notasFiscaisPendentes: NotaFiscal[] = [
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Tomate, Alface, Batata",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
  {
    numNF: 12345,
    date: "2024/09/05",
    quantity: "100",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Arroz, Feijão, Macarrão, Óleo de cozinha",
  },
  {
    numNF: 67890,
    date: "2024/09/06",
    quantity: "50",
    company: "Empresa 2",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Sacos plásticos, Etiquetas adesivas",
  },
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Refrigerantes, Cervejas, Sucos, Água mineral",
  },
  {
    numNF: 98765,
    date: "2024/09/08",
    quantity: "150",
    company: "Empresa 4",
    supplier: "Fornecedor X",
    description: "Detergente, Sabão em pó, Água sanitária, Esponjas",
  },
];

export const notasFiscaisAceitas: NotaFiscal[] = [
  {
    numNF: 54321,
    date: "2024/09/07",
    quantity: "200",
    company: "Empresa 3",
    supplier: "Fornecedor X",
    description: "Água Mineral, Refrigerantes, Cervejas",
  },
  {
    numNF: 67891,
    date: "2024/09/09",
    quantity: "120",
    company: "Empresa 5",
    supplier: "Fornecedor X",
    description: "Fogões industriais, Panelas de pressão, Freezer",
  },
  {
    numNF: 13579,
    date: "2024/09/10",
    quantity: "80",
    company: "Empresa 6",
    supplier: "Fornecedor X",
    description: "Facas, Colheres de aço inox, Tábua de corte",
  },
  {
    numNF: 24680,
    date: "2024/09/11",
    quantity: "300",
    company: "Empresa 7",
    supplier: "Fornecedor X",
    description: "Tomates, Alfaces, Pimentões, Cenouras",
  },
];

export const notasFiscaisRejeitadas: NotaFiscal[] = [
  {
    numNF: 12346,
    date: "2024/09/05",
    quantity: "90",
    company: "Empresa 1",
    supplier: "Fornecedor X",
    description: "Sabão em pó, Desinfetante, Água sanitária",
  },
  {
    numNF: 67892,
    date: "2024/09/06",
    quantity: "30",
    company: "Empresa 8",
    supplier: "Fornecedor X",
    description: "Caixas de papelão, Fitas adesivas, Plásticos bolha",
  },
  {
    numNF: 13580,
    date: "2024/09/07",
    quantity: "180",
    company: "Empresa 9",
    supplier: "Fornecedor X",
    description: "Cervejas vencidas, Refrigerantes vencidos",
  },
  {
    numNF: 98766,
    date: "2024/09/08",
    quantity: "50",
    company: "Empresa 10",
    supplier: "Fornecedor X",
    description: "Papéis A4, Canetas, Clipes de papel",
  },
];

export const companies = [
  {
    name: "Empresa 1",
    value: "Empresa 1",
  },
  {
    name: "Empresa 2",
    value: "Empresa 2",
  },
  {
    name: "Empresa 3",
    value: "Empresa 3",
  },
  {
    name: "Empresa 4",
    value: "Empresa 4",
  },
  {
    name: "Empresa 5",
    value: "Empresa 5",
  },
];
