export const payments = [
  {
    document_number: "000120568",
    company: { name: "FusionWare" },
    date_document: new Date("2024-09-01"),
    document: { name: "Boleto" },
    account_plan: {
      name: "Despesas com Produção/Serviço",
      abbreviation: "DPS",
      account: { name: "Bebidas (Diversos)" },
    },
    project: { name: "Strategis - BPO Financeiro" },
    expense_type: "Despesa Fixa",
    recurrence: "Recorrente",
    supplier: { name: "Fornecedor A" },
    bank: { name: "CC Itaú" },
    value: 1500,
    installment: "Única",
    value_payed: 1500,
    date_deadline: new Date("2024-09-10"),
    date_payment: new Date("2024-09-09"),
    confirmed_status: "Confirmada",
    payed_status: "Pago",
    group: { name: "Despesas com Produção/Serviço" },
    products: [{ name: "Produto 1" }, { name: "Produto 2" }],
  },
  {
    document_number: "000124798",
    company: { name: "Apex Innovations Filial" },
    date_document: new Date("2024-09-02"),
    document: { name: "Cartão Crédito" },
    account_plan: {
      name: "Despesas Administrativas Outras",
      abbreviation: "DOA",
      account: { name: "Uber (Outros)" },
    },
    project: { name: "Strategis - FidelizClub" },
    expense_type: "Despesa Variável",
    recurrence: "Avulsa",
    supplier: { name: "Fornecedor B" },
    bank: undefined,
    value: 300,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date("2024-09-15"),
    date_payment: undefined,
    confirmed_status: "Confirmada",
    payed_status: "Em Aberto",
    group: { name: "Despesas com Pessoal" },
    products: [{ name: "Produto 1" }, { name: "Produto 2" }],
  },
  {
    document_number: "000892359",
    company: { name: "Apex Innovations Matriz" },
    date_document: new Date("2024-08-31"),
    document: { name: "Transf/PIX/TED/DOC" },
    account_plan: {
      name: "Receitas de Vendas (Delivery)",
      abbreviation: "RVD",
      account: { name: "Vendas - Delivery Ifood" },
    },
    project: { name: "Strategis - Geral" },
    expense_type: "Receita",
    recurrence: "Avulsa",
    supplier: { name: "Fornecedor C" },
    bank: { name: "PagSeguro (Loja)" },
    value: 1200,
    installment: "Única",
    value_payed: 1200,
    date_deadline: new Date("2024-09-05"),
    date_payment: new Date("2024-09-03"),
    confirmed_status: "Confirmada",
    payed_status: "Pago",
    group: { name: "Receitas de Vendas (Loja)" },
    products: [{ name: "Produto 1" }, { name: "Produto 2" }],
  },
  {
    document_number: "000782354",
    company: { name: "Quantum Dynamics" },
    date_document: new Date("2024-09-01"),
    document: { name: "Boleto" },
    account_plan: {
      name: "Despesas com Pessoal",
      abbreviation: "DPE",
      account: { name: "Alimentação (Diversas)" },
    },
    project: { name: "Strategis - Geral" },
    expense_type: "Despesa Fixa",
    recurrence: "Recorrente",
    supplier: { name: "Fornecedor A" },
    bank: { name: "CC Itaú" },
    value: 3000,
    installment: "Única",
    value_payed: 3000,
    date_deadline: new Date("2024-09-10"),
    date_payment: new Date("2024-09-08"),
    confirmed_status: "Confirmada",
    payed_status: "Pago",
    group: { name: "Despesas com Pessoal" },
    products: [{ name: "Produto 3" }, { name: "Produto 4" }],
  },
  {
    document_number: "000543731",
    company: { name: "TechNova Filial" },
    date_document: new Date("2024-09-05"),
    document: { name: "NF" },
    account_plan: {
      name: "Despesas com Produção/Serviço",
      abbreviation: "DPS",
      account: { name: "Bebidas (Diversos)" },
    },
    project: { name: "Strategis - FidelizClub" },
    expense_type: "Despesa Variável",
    recurrence: "Parcelas",
    supplier: { name: "Fornecedor B" },
    bank: { name: "CC Santander" },
    value: 4500,
    installment: "2/3",
    value_payed: 1500,
    date_deadline: new Date("2024-09-15"),
    date_payment: new Date("2024-09-14"),
    confirmed_status: "Confirmada",
    payed_status: "Pago",
    group: { name: "Despesas com Produção/Serviço" },
    products: [{ name: "Produto 1" }, { name: "Produto 3" }],
  },
  {
    document_number: "000457643",
    company: { name: "TechNova Matriz" },
    date_document: new Date("2024-08-20"),
    document: { name: "Recibo" },
    account_plan: {
      name: "Receitas de Vendas (Delivery)",
      abbreviation: "DPS",
      account: { name: "Vendas - Delivery Próprio" },
    },
    project: { name: "Strategis - Geral" },
    expense_type: "Receita",
    recurrence: "Avulsa",
    supplier: { name: "Fornecedor C" },
    bank: undefined,
    value: 7500,
    installment: "Única",
    value_payed: undefined,
    date_deadline: new Date("2024-09-01"),
    date_payment: undefined,
    confirmed_status: "Confirmada",
    payed_status: "Em Aberto",
    group: { name: "Receita de Venads (Delivery)" },
    products: [{ name: "Produto 2" }, { name: "Produto 4" }],
  },
  {
    document_number: "000823612",
    company: { name: "Alimentos WCW" },
    date_document: new Date("2024-09-12"),
    document: { name: "Transf/PIX/TED/DOC" },
    account_plan: {
      name: "Investimentos e Retiradas",
      abbreviation: "DIR",
      account: { name: "Utensílios (I)" },
    },
    project: { name: "Strategis - BPO Financeiro" },
    expense_type: "Despesa Fixa",
    recurrence: "Recorrente",
    supplier: { name: "Fornecedor D" },
    bank: { name: "CRT Itaú Master" },
    value: 15000,
    installment: "Única",
    value_payed: 15000,
    date_deadline: new Date("2024-09-25"),
    date_payment: new Date("2024-09-24"),
    confirmed_status: "Confirmada",
    payed_status: "Pago",
    group: { name: "Investimentos e Retiradas" },
    products: [
      { name: "Produto 1" },
      { name: "Produto 2" },
      { name: "Produto 5" },
    ],
  },
];
