import { type Product } from "~/app/ConfiguracoesGerais/CadastroDeProdutos/_components/productsData";
import { type User } from "~/components/navbar/_components/userData";

export type Operation = {
  date: Date;
  operator: User;
  operation: string;
  products: Product[];
};

export const operations: Operation[] = [
  {
    date: new Date(2024, 9, 24),
    operator: {
      name: "Operador 1",
      role: "Operador",
      phone: "(61) 99999-9999",
      company: "Alimentos WCW",
    },
    operation: "Importação de Nota Fiscal",
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor A" }, { name: "Fornecedor B" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        buy_quantity: "100",
        buy_day: "Segunda",
        stock_current: "200",
        stock_min: "50",
        stock_max: "300",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
        permission: true,
      },
      {
        name: "Carne Bovina",
        code: "1002",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor B" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "50",
        buy_day: "Terça",
        stock_current: "120",
        stock_min: "30",
        stock_max: "200",
        type_of_control: { description: "Produtos de Produção" },
        product_category: { description: "Carnes - In Natura" },
        sector_of_use: { description: "Cozinha" },
        address: {
          stock: "Estoque Cozinha",
          storage: "Armário 2",
          shelf: "Prateleira 3",
        },
        permission: false,
      },
      {
        name: "Sabão em Pó",
        code: "1004",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor D" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "30",
        buy_day: "Quinta",
        stock_current: "80",
        stock_min: "20",
        stock_max: "100",
        type_of_control: { description: "Produtos de Limpeza" },
        product_category: { description: "Produtos - Limpeza" },
        sector_of_use: { description: "Serviços Gerais" },
        address: {
          stock: "Estoque Geral",
          storage: "Zona 2",
          shelf: "Prateleira 7",
        },
        permission: false,
      },
      {
        name: "Vinho Tinto",
        code: "1005",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor E" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        buy_quantity: "120",
        buy_day: "Sexta",
        stock_current: "150",
        stock_min: "50",
        stock_max: "250",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
        permission: true,
      },
    ],
  },
  {
    date: new Date(2024, 9, 24),
    operator: {
      name: "Estoquista 2",
      role: "Operador",
      phone: "(61) 99999-9999",
      company: "TechNova Filial",
    },
    operation: "Inventário de Estoque",
    products: [
      {
        name: "Cerveja Pilsen",
        code: "1001",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor A" }, { name: "Fornecedor B" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        buy_quantity: "100",
        buy_day: "Segunda",
        stock_current: "200",
        stock_min: "50",
        stock_max: "300",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Cervejas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Bar",
          storage: "Armário 1",
          shelf: "Prateleira 1",
        },
        permission: true,
      },
      {
        name: "Carne Bovina",
        code: "1002",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor B" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "50",
        buy_day: "Terça",
        stock_current: "120",
        stock_min: "30",
        stock_max: "200",
        type_of_control: { description: "Produtos de Produção" },
        product_category: { description: "Carnes - In Natura" },
        sector_of_use: { description: "Cozinha" },
        address: {
          stock: "Estoque Cozinha",
          storage: "Armário 2",
          shelf: "Prateleira 3",
        },
        permission: false,
      },
      {
        name: "Carne Moída",
        code: "1006",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor B" }],
        buy_or_production: "Produto de Produção",
        parent_product: "Carne Bovina",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "20",
        buy_day: "Quarta",
        stock_current: "60",
        stock_min: "10",
        stock_max: "100",
        type_of_control: { description: "Produtos de Produção" },
        product_category: { description: "Carnes - Processadas" },
        sector_of_use: { description: "Cozinha" },
        address: {
          stock: "Estoque Cozinha",
          storage: "Armário 2",
          shelf: "Prateleira 4",
        },
        permission: false,
      },
      {
        name: "Água Mineral",
        code: "1003",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor C" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        buy_quantity: "200",
        buy_day: "Quarta",
        stock_current: "250",
        stock_min: "100",
        stock_max: "400",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Águas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Salão",
          storage: "Zona 1",
          shelf: "Prateleira 6",
        },
        permission: true,
      },
    ],
  },
  {
    date: new Date(2024, 9, 24),
    operator: {
      name: "Estoquista 3",
      role: "Operador",
      phone: "(61) 99999-9999",
      company: "Quantum Dynamics",
    },
    operation: "Ajuste de Estoque",
    products: [
      {
        name: "Carne Moída",
        code: "1006",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor B" }],
        buy_or_production: "Produto de Produção",
        parent_product: "Carne Bovina",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "20",
        buy_day: "Quarta",
        stock_current: "60",
        stock_min: "10",
        stock_max: "100",
        type_of_control: { description: "Produtos de Produção" },
        product_category: { description: "Carnes - Processadas" },
        sector_of_use: { description: "Cozinha" },
        address: {
          stock: "Estoque Cozinha",
          storage: "Armário 2",
          shelf: "Prateleira 4",
        },
        permission: false,
      },
      {
        name: "Água Mineral",
        code: "1003",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor C" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Pacote",
          abbreviation: "PCT",
          unitsPerPack: 12,
        },
        buy_quantity: "200",
        buy_day: "Quarta",
        stock_current: "250",
        stock_min: "100",
        stock_max: "400",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Águas" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Salão",
          storage: "Zona 1",
          shelf: "Prateleira 6",
        },
        permission: true,
      },
      {
        name: "Sabão em Pó",
        code: "1004",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor D" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Kilograma",
          abbreviation: "KG",
          unitsPerPack: 1,
        },
        buy_quantity: "30",
        buy_day: "Quinta",
        stock_current: "80",
        stock_min: "20",
        stock_max: "100",
        type_of_control: { description: "Produtos de Limpeza" },
        product_category: { description: "Produtos - Limpeza" },
        sector_of_use: { description: "Serviços Gerais" },
        address: {
          stock: "Estoque Geral",
          storage: "Zona 2",
          shelf: "Prateleira 7",
        },
        permission: false,
      },
      {
        name: "Vinho Tinto",
        code: "1005",
        status: "Ativo",
        suppliers: [{ name: "Fornecedor E" }],
        buy_or_production: "Produto de Compra",
        buy_unit: {
          description: "Fardo",
          abbreviation: "FRD",
          unitsPerPack: 10,
        },
        buy_quantity: "120",
        buy_day: "Sexta",
        stock_current: "150",
        stock_min: "50",
        stock_max: "250",
        type_of_control: { description: "Produtos de Bar" },
        product_category: { description: "Bebidas - Vinho" },
        sector_of_use: { description: "Bar" },
        address: {
          stock: "Estoque Padaria",
          storage: "Zona 3",
          shelf: "Prateleira 10",
        },
        permission: true,
      },
    ],
  },
];
