export const account_plans: {
  name: string;
  abbreviation: string;
  accounts: { name: string }[];
}[] = [
  {
    name: "Despesas com Produção/Serviço",
    abbreviation: "DPS",
    accounts: [
      { name: "Bebidas (Chopp)" },
      { name: "Bebidas (Diversos)" },
      { name: "Bebidas (Xapore)" },
      { name: "Bobinas e Etiquetas" },
      { name: "Carvão" },
      { name: "Embalagem (Personalizada)" },
      { name: "Embalagem (Simples)" },
      { name: "Gás" },
      { name: "Gelo" },
      { name: "Hortifrut" },
      { name: "Insumos Diversos" },
      { name: "Lenha" },
      { name: "Material de Escritório" },
      { name: "Não Categorizados" },
      { name: "Pães de hambúrguer" },
      { name: "Pão de alho" },
      { name: "Insumos (Brinquedoteca)" },
      { name: "Proteína (Bovina)" },
      { name: "Proteína (Diversos)" },
      { name: "Proteína (Embutidos)" },
      { name: "Proteína (Queijos)" },
      { name: "Proteína (Suína)" },
      { name: "Sobremesas" },
      { name: "Temperos" },
      { name: "Material de Uso e Consumo" },
      { name: "Proteína (Ovos)" },
      { name: "Proteína (Aves)" },
      { name: "Frutas Congeladas" },
      { name: "Batata Congelada" },
    ],
  },
  {
    name: "Despesas com Ocupação",
    abbreviation: "DOC",
    accounts: [
      { name: "Água e Esgoto" },
      { name: "Alarme da loja" },
      { name: "Locação Imóvel (Aluguel + IPTU + Seguros)" },
      { name: "Containner de lixo" },
      { name: "Material de Limpeza e Conservação" },
      { name: "Eletricista" },
      { name: "Energia Elétrica" },
      { name: "Internet" },
      { name: "IPTU" },
      { name: "Manutenção Geral" },
      { name: "Manutenção Refrigeração" },
      { name: "Manutenção de Máquinas, Móveis e Equipamentos" },
      { name: "Motoboy Delivery" },
      { name: "Obras e Reformas(D)" },
      { name: "Seguro da Loja" },
      { name: "Telefonia (Celular/Fixo)" },
      { name: "Dedetização" },
    ],
  },
  {
    name: "Despesas com Terceiros",
    abbreviation: "DTC",
    accounts: [
      { name: "Advogados" },
      { name: "BPO-Financeiro" },
      { name: "Consultor de Negócios" },
      { name: "Contabilidade" },
      { name: "Dedetização" },
      { name: "Designer de Imagens" },
      { name: "Especialista em RH" },
      { name: "Limpeza e Conservação" },
      { name: "Músico" },
      { name: "Nutricionista" },
      { name: "Publicidade e Propaganda" },
      { name: "Reforma e Construção" },
      { name: "Segurança moto" },
      { name: "Serviços de TI" },
      { name: "Serviços Jurídicos" },
      { name: "Webdesigner" },
    ],
  },
  {
    name: "Despesas com Pessoal",
    abbreviation: "DPE",
    accounts: [
      { name: "Alimentação (Diversas)" },
      { name: "Assistência Médica" },
      { name: "Assistência Odonto" },
      { name: "Bonificação (Diversos)" },
      { name: "Bonificação 10%" },
      { name: "Bonificação 10% (Adiantamento)" },
      { name: "Confraternização" },
      { name: "Educação (Cursos e Livros)" },
      { name: "Exames Médicos" },
      { name: "Férias" },
      { name: "FGTS" },
      { name: "FGTS (Multa)" },
      { name: "Freelancer" },
      { name: "INSS" },
      { name: "INSS (Parcelamento)" },
      { name: "Insumos para Funcionários" },
      { name: "IRRF" },
      { name: "Mensalidade Sindicato" },
      { name: "Plano de Saúde / Exames" },
      { name: "Pró-Labore (Jefferson)" },
      { name: "Pró-Labore (Jonathan e Ágatha)" },
      { name: "Reembolso Funcionário" },
      { name: "Rescisão" },
      { name: "RH (A Classificar)" },
      { name: "Salário (13o Salário)" },
      { name: "Salário (Adiantamento)" },
      { name: "Salário (Bonificação)" },
      { name: "Salário (Dobras / Diárias)" },
      { name: "Salário (Folha)" },
      { name: "Salário (Gratificações)" },
      { name: "Seguro de Vida (Funcionários)" },
      { name: "Transporte (VT)" },
      { name: "Uniformes" },
      { name: "Vale Refeição/Alimentação" },
      { name: "Vestuário" },
    ],
  },
  {
    name: "Deduções sobre Vendas",
    abbreviation: "DSV",
    accounts: [
      { name: "Antecipação" },
      { name: "COFINS" },
      { name: "DAS - Simples Nacional" },
      { name: "ICMS" },
      { name: "IPI" },
      { name: "ISS" },
      { name: "PIS" },
    ],
  },
  {
    name: "Impostos Diretos",
    abbreviation: "DID",
    accounts: [{ name: "ID" }, { name: "CSLL" }],
  },
  {
    name: "Despesas Comerciais/Vendas",
    abbreviation: "DCV",
    accounts: [
      { name: "Alimentação Diversos" },
      { name: "Comissão (Boleto/Pix)" },
      { name: "Comissão (Diversas)" },
      { name: "Comissão (Emissão de Boletos)" },
      { name: "Comissão (Indicação)" },
      { name: "Deslocamento" },
      { name: "DCV" },
      { name: "Estornos" },
      { name: "Eventos e Network" },
      { name: "Financiamento Veículo" },
      { name: "Gasolina" },
      { name: "Impressões para Marketing" },
      { name: "Logística" },
      { name: "Gestor de Marketing" },
      { name: "Marketing Outdoor" },
      { name: "Contas de comida" },
      { name: "Marketing Televisão" },
      { name: "Materiais para Marketing" },
      { name: "Material impresso | Cardápios" },
      { name: "Programa de Fidelidade" },
      { name: "Redes Sociais" },
      { name: "Seguro Veículo" },
      { name: "Trafego pago" },
      { name: "Transporte ADM" },
      { name: "Uber" },
      { name: "Viagens e Deslocamento" },
      { name: "Vídeos" },
    ],
  },
  {
    name: "Despesas Administrativas Outras",
    abbreviation: "DOA",
    accounts: [
      { name: "Financiamento Veiculo" },
      { name: "Gasolina" },
      { name: "Manutenção de Veículos" },
      { name: "Marcas e Patentes" },
      { name: "Material de Escritório" },
      { name: "Seguro Veículo" },
      { name: "Uber (Administrativo)" },
      { name: "Uber (Outros)" },
    ],
  },
  {
    name: "Despesas com Tecnologia",
    abbreviation: "DTC",
    accounts: [
      { name: "Aplicativos" },
      { name: "Domínios de Sites" },
      { name: "Ferramenta do Portal" },
      { name: "Hospedagem de Sites/Emails" },
      { name: "Relógio de Ponto" },
      { name: "Sistema de Vendas" },
      { name: "Software de Gestão" },
      { name: "Software Gestão Financeira" },
      { name: "Spotify" },
      { name: "Tecnologia Diversos" },
    ],
  },
  {
    name: "Despesas Financeiras",
    abbreviation: "DFI",
    accounts: [
      { name: "Anuidade de Cartão" },
      { name: "Cartório" },
      { name: "Cheque Especial" },
      { name: "Despachante" },
      { name: "Despesa Financeira (A Categorizar)" },
      { name: "Estorno de Vendas" },
      { name: "Juros" },
      { name: "Multas" },
      { name: "Pagamento de Empréstimo" },
      { name: "Reembolso" },
      { name: "SCP" },
      { name: "Taxas Bancárias Diversas" },
      { name: "Taxas de IOF" },
      { name: "Taxas de Pix" },
      { name: "Taxas de TED/DOC" },
      { name: "Pagamento de Cartão de Crédito" },
    ],
  },
  {
    name: "Investimentos e Retiradas",
    abbreviation: "DIR",
    accounts: [
      { name: "Imóveis" },
      { name: "Máquinas, Móveis e Equipamentos (I)" },
      { name: "Móveis" },
      { name: "Reformas (I)" },
      { name: "Pagamento de Empréstimo (Ex-Sócio)" },
      { name: "Renegociação de Dívida - Anterior a Março/2024" },
      { name: "Retiradas (Jonathan e Ágatha)" },
      { name: "Retiradas (Jefferson)" },
      { name: "Utensílios (I)" },
      { name: "Veículos" },
      { name: "Pagamento de Empréstimo" },
    ],
  },
  {
    name: "Receitas de Vendas (Loja)",
    abbreviation: "RVL",
    accounts: [
      { name: "Vendas - Salão/Balcão" },
      { name: "Vendas - Incentivos (Parceiros)" },
      { name: "Vendas - Funcionários" },
    ],
  },
  {
    name: "Receitas de Vendas (Delivery)",
    abbreviation: "RVD",
    accounts: [
      { name: "Vendas - Delivery Próprio" },
      { name: "Vendas - Delivery Ifood" },
    ],
  },
  {
    name: "Receitas de Vendas (Eventos)",
    abbreviation: "RVE",
    accounts: [
      { name: "Vendas - Eventos (Próprios)" },
      { name: "Vendas - Eventos (Participação)" },
    ],
  },
  {
    name: "Receitas de Reembolsos",
    abbreviation: "RRB",
    accounts: [
      { name: "Depósitos Indevidos" },
      { name: "Reembolso Diversos" },
      { name: "Ressarcimento" },
      { name: "Reembolso Bancário" },
      { name: "Reembolso de Despesas Canceladas" },
    ],
  },
  {
    name: "Receitas Diversas",
    abbreviation: "RDI",
    accounts: [{ name: "Outras Receitas" }, { name: "Depósitos Indevidos" }],
  },
  {
    name: "Receitas Financeiras",
    abbreviation: "RFI",
    accounts: [
      { name: "Empréstimos Bancários" },
      { name: "Empréstimos de Terceiros" },
      { name: "Rendimentos de Aplicações" },
    ],
  },
];
