export const categories: {
  name: string;
}[] = [
  { name: "Acompanhamento" },
  { name: "Bebidas" },
  { name: "Bebidas - Águas" },
  { name: "Bebidas - Café" },
  { name: "Bebidas - Cervejas" },
  { name: "Bebidas - Chop" },
  { name: "Bebidas - Destilados" },
  { name: "Bebidas - Energéticos" },
  { name: "Bebidas - Refrigerantes" },
  { name: "Bebidas - Vinho" },
  { name: "Bebidas - Xaropes" },
  { name: "Carnes" },
  { name: "Carnes - Em Processo" },
  { name: "Carnes - Funcionários" },
  { name: "Carnes - In Natura" },
  { name: "Carnes - Porcionadas" },
  { name: "Embalagens" },
  { name: "Embalagens - A vácuo" },
  { name: "Embalagens - Evento" },
  { name: "Entradas" },
  { name: "Equipamento" },
  { name: "Equipamento - Refrigeração" },
  { name: "Equipamento - Bar" },
  { name: "Equipamento - Cozinha" },
  { name: "Equipamento - Eletrônico" },
  { name: "Equipamento - Limpeza" },
  { name: "Funcionários" },
  { name: "Hortifruti" },
  { name: "Insumos" },
  { name: "Mobiliário" },
  { name: "Mobiliário - Salão" },
  { name: "Mobiliário - Assentos Salão" },
  { name: "Mobiliário - Mesas Salão" },
  { name: "Mobiliário - Cozinha" },
  { name: "Molhos" },
  { name: "Pães" },
  { name: "Produtos" },
  { name: "Produtos - Limpeza" },
  { name: "Queijos" },
  { name: "Queijos - Porcionados" },
  { name: "Queima" },
  { name: "Sobremesas" },
  { name: "Temperos" },
  { name: "Utensilhos" },
  { name: "Utensilhos - Bar" },
  { name: "Utensilhos - Cozinho" },
  { name: "Utensilhos - Quadro" },
];
