export const customReportOptions: { description: string }[] = [
  { description: "Nome" },
  { description: "Código" },
  { description: "Fornecedores" },
  { description: "Status" },
  { description: "Produto Pai" },
  { description: "Unidade de Compra" },
  { description: "Quantidade de Compra" },
  { description: "Dia de Compra" },
  { description: "Estoque Atual" },
  { description: "Estoque Mínimo" },
  { description: "Estoque Máximo" },
  { description: "Tipo de Controle" },
  { description: "Categoria do Produto" },
  { description: "Setor de Utilização" },
  { description: "Endereço do Estoque" },
  { description: "Usuários com Permissão" },
];
