export const modules = [
  "Cadastrar Empresas",
  "Cadastrar Fornecedores",
  "Cadastrar Produtos",
  "Cadastrar Estoques",
  "Cadastrar Parâmetros Gerais",
  "Cadastrar Usuários",
  "Cadastrar Perfis de Acesso",
  "Importar NFs de Qualquer Empresa",
  "Dar Entrada de Mercadorias",
  "Dar Saída de Mercadorias",
  "Comprar Mercadorias",
  "Fazer Inventários",
  "Fazer Ajustes de Estoque",
  "Requisitar Mercadorias do Estoque",
  "Dar Aceite de Mercadorias Recebidas",
  "Checar Status de Requisições",
  "Gerar Relatórios de Aviso de Estoque",
  "Gerar Relatórios Personalizados de Estoque",
  "Checar Histórico de Operações",
  "Checar Histórico de Pagamentos",
];
