export const modules = [
  { name: "Cadastrar Empresas", code: 1 },
  { name: "Cadastrar Fornecedores", code: 2 },
  { name: "Cadastrar Produtos", code: 3 },
  { name: "Cadastrar Estoques", code: 4 },
  { name: "Cadastrar Parâmetros Gerais", code: 5 },
  { name: "Cadastrar Usuários", code: 6 },
  { name: "Cadastrar Perfis de Acesso", code: 7 },
  { name: "Importar NFs de Qualquer Empresa", code: 8 },
  { name: "Dar Entrada de Mercadorias", code: 9 },
  { name: "Dar Saída de Mercadorias", code: 10 },
  { name: "Comprar Mercadorias", code: 11 },
  { name: "Fazer Inventários", code: 12 },
  { name: "Fazer Ajustes de Estoque", code: 13 },
  { name: "Requisitar Mercadorias do Estoque", code: 14 },
  { name: "Dar Aceite de Mercadorias Recebidas", code: 15 },
  { name: "Checar Status de Requisições", code: 16 },
  { name: "Gerar Relatórios de Aviso de Estoque", code: 17 },
  { name: "Gerar Relatórios Personalizados de Estoque", code: 18 },
  { name: "Checar Histórico de Operações", code: 19 },
  { name: "Checar Histórico de Pagamentos", code: 20 },
];
